# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ui_PyQt_xufang(object):
    def setupUi(self, Ui_PyQt_xufang):
        Ui_PyQt_xufang.setObjectName("Ui_PyQt_xufang")
        Ui_PyQt_xufang.setEnabled(True)
        Ui_PyQt_xufang.resize(416, 645)
        Ui_PyQt_xufang.setMaximumSize(QtCore.QSize(419, 645))
        self.centralwidget = QtWidgets.QWidget(Ui_PyQt_xufang)
        self.centralwidget.setObjectName("centralwidget")
        self.pBtn_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_24.setGeometry(QtCore.QRect(249, 484, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_24.setFont(font)
        self.pBtn_24.setObjectName("pBtn_24")
        self.pBtn_29 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_29.setGeometry(QtCore.QRect(249, 528, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_29.setFont(font)
        self.pBtn_29.setObjectName("pBtn_29")
        self.pBtn_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_17.setGeometry(QtCore.QRect(83, 440, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_17.setFont(font)
        self.pBtn_17.setObjectName("pBtn_17")
        self.pBtn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_8.setGeometry(QtCore.QRect(166, 350, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_8.setFont(font)
        self.pBtn_8.setObjectName("pBtn_8")
        self.pBtn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_4.setGeometry(QtCore.QRect(249, 304, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_4.setFont(font)
        self.pBtn_4.setObjectName("pBtn_4")
        self.pBtn_27 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_27.setGeometry(QtCore.QRect(83, 528, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_27.setFont(font)
        self.pBtn_27.setObjectName("pBtn_27")
        self.pBtn_28 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_28.setGeometry(QtCore.QRect(166, 528, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_28.setFont(font)
        self.pBtn_28.setObjectName("pBtn_28")
        self.pBtn_32 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_32.setGeometry(QtCore.QRect(83, 572, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_32.setFont(font)
        self.pBtn_32.setObjectName("pBtn_32")
        self.pBtn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_9.setGeometry(QtCore.QRect(249, 350, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_9.setFont(font)
        self.pBtn_9.setObjectName("pBtn_9")
        self.pBtn_31 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_31.setGeometry(QtCore.QRect(0, 572, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_31.setFont(font)
        self.pBtn_31.setObjectName("pBtn_31")
        self.pBtn_35 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_35.setGeometry(QtCore.QRect(332, 572, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_35.setFont(font)
        self.pBtn_35.setObjectName("pBtn_35")
        self.pBtn_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_19.setGeometry(QtCore.QRect(249, 440, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_19.setFont(font)
        self.pBtn_19.setObjectName("pBtn_19")
        self.pBtn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_5.setGeometry(QtCore.QRect(332, 304, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_5.setFont(font)
        self.pBtn_5.setObjectName("pBtn_5")
        self.pBtn_34 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_34.setGeometry(QtCore.QRect(249, 572, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_34.setFont(font)
        self.pBtn_34.setObjectName("pBtn_34")
        self.pBtn_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_22.setGeometry(QtCore.QRect(83, 484, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_22.setFont(font)
        self.pBtn_22.setObjectName("pBtn_22")
        self.pBtn_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_11.setGeometry(QtCore.QRect(0, 396, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_11.setFont(font)
        self.pBtn_11.setObjectName("pBtn_11")
        self.Displaytext = QtWidgets.QTextEdit(self.centralwidget)
        self.Displaytext.setGeometry(QtCore.QRect(0, 0, 418, 304))
        self.Displaytext.setLineWidth(1)
        self.Displaytext.setTabStopWidth(80)
        self.Displaytext.setCursorWidth(3)
        self.Displaytext.setObjectName("Displaytext")
        self.pBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_2.setGeometry(QtCore.QRect(83, 304, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_2.setFont(font)
        self.pBtn_2.setIconSize(QtCore.QSize(20, 20))
        self.pBtn_2.setObjectName("pBtn_2")
        self.pBtn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_6.setGeometry(QtCore.QRect(0, 350, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_6.setFont(font)
        self.pBtn_6.setObjectName("pBtn_6")
        self.pBtn_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_14.setGeometry(QtCore.QRect(249, 396, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_14.setFont(font)
        self.pBtn_14.setObjectName("pBtn_14")
        self.pBtn_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_20.setGeometry(QtCore.QRect(332, 440, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_20.setFont(font)
        self.pBtn_20.setObjectName("pBtn_20")
        self.pBtn_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_12.setGeometry(QtCore.QRect(83, 396, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_12.setFont(font)
        self.pBtn_12.setObjectName("pBtn_12")
        self.pBtn_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_13.setGeometry(QtCore.QRect(166, 396, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_13.setFont(font)
        self.pBtn_13.setObjectName("pBtn_13")
        self.pBtn_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_25.setGeometry(QtCore.QRect(332, 484, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_25.setFont(font)
        self.pBtn_25.setObjectName("pBtn_25")
        self.pBtn_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_21.setGeometry(QtCore.QRect(0, 484, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_21.setFont(font)
        self.pBtn_21.setObjectName("pBtn_21")
        self.pBtn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_1.setEnabled(True)
        self.pBtn_1.setGeometry(QtCore.QRect(0, 304, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_1.setFont(font)
        self.pBtn_1.setObjectName("pBtn_1")
        self.pBtn_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_18.setGeometry(QtCore.QRect(166, 440, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_18.setFont(font)
        self.pBtn_18.setObjectName("pBtn_18")
        self.pBtn_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_10.setGeometry(QtCore.QRect(332, 350, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_10.setFont(font)
        self.pBtn_10.setObjectName("pBtn_10")
        self.pBtn_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_23.setGeometry(QtCore.QRect(166, 484, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_23.setFont(font)
        self.pBtn_23.setObjectName("pBtn_23")
        self.pBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_3.setGeometry(QtCore.QRect(166, 304, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_3.setFont(font)
        self.pBtn_3.setIconSize(QtCore.QSize(20, 20))
        self.pBtn_3.setAutoRepeat(False)
        self.pBtn_3.setAutoExclusive(False)
        self.pBtn_3.setAutoRepeatDelay(300)
        self.pBtn_3.setObjectName("pBtn_3")
        self.pBtn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_7.setGeometry(QtCore.QRect(83, 350, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_7.setFont(font)
        self.pBtn_7.setObjectName("pBtn_7")
        self.pBtn_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_16.setGeometry(QtCore.QRect(0, 440, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_16.setFont(font)
        self.pBtn_16.setObjectName("pBtn_16")
        self.pBtn_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_15.setGeometry(QtCore.QRect(332, 396, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_15.setFont(font)
        self.pBtn_15.setObjectName("pBtn_15")
        self.pBtn_30 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_30.setGeometry(QtCore.QRect(332, 528, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_30.setFont(font)
        self.pBtn_30.setObjectName("pBtn_30")
        self.pBtn_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_26.setGeometry(QtCore.QRect(0, 528, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_26.setFont(font)
        self.pBtn_26.setObjectName("pBtn_26")
        self.pBtn_33 = QtWidgets.QPushButton(self.centralwidget)
        self.pBtn_33.setGeometry(QtCore.QRect(166, 572, 85, 48))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.pBtn_33.setFont(font)
        self.pBtn_33.setObjectName("pBtn_33")
        Ui_PyQt_xufang.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_PyQt_xufang)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 416, 26))
        self.menubar.setObjectName("menubar")
        Ui_PyQt_xufang.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_PyQt_xufang)
        self.statusbar.setObjectName("statusbar")
        Ui_PyQt_xufang.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_PyQt_xufang)
        self.pBtn_1.clicked.connect(self.Displaytext.show)
        QtCore.QMetaObject.connectSlotsByName(Ui_PyQt_xufang)
        Ui_PyQt_xufang.setTabOrder(self.Displaytext, self.pBtn_1)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_1, self.pBtn_2)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_2, self.pBtn_3)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_3, self.pBtn_4)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_4, self.pBtn_5)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_5, self.pBtn_6)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_6, self.pBtn_7)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_7, self.pBtn_8)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_8, self.pBtn_9)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_9, self.pBtn_10)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_10, self.pBtn_11)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_11, self.pBtn_12)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_12, self.pBtn_13)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_13, self.pBtn_14)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_14, self.pBtn_15)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_15, self.pBtn_16)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_16, self.pBtn_17)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_17, self.pBtn_18)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_18, self.pBtn_19)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_19, self.pBtn_20)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_20, self.pBtn_21)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_21, self.pBtn_22)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_22, self.pBtn_23)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_23, self.pBtn_24)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_24, self.pBtn_25)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_25, self.pBtn_26)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_26, self.pBtn_27)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_27, self.pBtn_28)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_28, self.pBtn_29)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_29, self.pBtn_30)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_30, self.pBtn_31)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_31, self.pBtn_32)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_32, self.pBtn_33)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_33, self.pBtn_34)
        Ui_PyQt_xufang.setTabOrder(self.pBtn_34, self.pBtn_35)

    def retranslateUi(self, Ui_PyQt_xufang):
        _translate = QtCore.QCoreApplication.translate
        Ui_PyQt_xufang.setWindowTitle(_translate("Ui_PyQt_xufang", "MainWindow"))
        self.pBtn_24.setText(_translate("Ui_PyQt_xufang", "6"))
        self.pBtn_29.setText(_translate("Ui_PyQt_xufang", "3"))
        self.pBtn_17.setText(_translate("Ui_PyQt_xufang", "7"))
        self.pBtn_8.setText(_translate("Ui_PyQt_xufang", "ln"))
        self.pBtn_4.setText(_translate("Ui_PyQt_xufang", "cos"))
        self.pBtn_27.setText(_translate("Ui_PyQt_xufang", "1"))
        self.pBtn_28.setText(_translate("Ui_PyQt_xufang", "2"))
        self.pBtn_32.setText(_translate("Ui_PyQt_xufang", "e"))
        self.pBtn_9.setText(_translate("Ui_PyQt_xufang", "("))
        self.pBtn_31.setText(_translate("Ui_PyQt_xufang", "change"))
        self.pBtn_35.setText(_translate("Ui_PyQt_xufang", "="))
        self.pBtn_19.setText(_translate("Ui_PyQt_xufang", "9"))
        self.pBtn_5.setText(_translate("Ui_PyQt_xufang", "tan"))
        self.pBtn_34.setText(_translate("Ui_PyQt_xufang", "."))
        self.pBtn_22.setText(_translate("Ui_PyQt_xufang", "4"))
        self.pBtn_11.setText(_translate("Ui_PyQt_xufang", "√x"))
        self.pBtn_2.setText(_translate("Ui_PyQt_xufang", "deg"))
        self.pBtn_6.setText(_translate("Ui_PyQt_xufang", "Xy"))
        self.pBtn_14.setText(_translate("Ui_PyQt_xufang", "%"))
        self.pBtn_20.setText(_translate("Ui_PyQt_xufang", "X"))
        self.pBtn_12.setText(_translate("Ui_PyQt_xufang", "C"))
        self.pBtn_13.setText(_translate("Ui_PyQt_xufang", "del"))
        self.pBtn_25.setText(_translate("Ui_PyQt_xufang", "-"))
        self.pBtn_21.setText(_translate("Ui_PyQt_xufang", "1/X"))
        self.pBtn_1.setText(_translate("Ui_PyQt_xufang", "2nd"))
        self.pBtn_18.setText(_translate("Ui_PyQt_xufang", "8"))
        self.pBtn_10.setText(_translate("Ui_PyQt_xufang", ")"))
        self.pBtn_23.setText(_translate("Ui_PyQt_xufang", "5"))
        self.pBtn_3.setText(_translate("Ui_PyQt_xufang", "sin"))
        self.pBtn_7.setText(_translate("Ui_PyQt_xufang", "lg"))
        self.pBtn_16.setText(_translate("Ui_PyQt_xufang", "X!"))
        self.pBtn_15.setText(_translate("Ui_PyQt_xufang", "/"))
        self.pBtn_30.setText(_translate("Ui_PyQt_xufang", "+"))
        self.pBtn_26.setText(_translate("Ui_PyQt_xufang", "pi"))
        self.pBtn_33.setText(_translate("Ui_PyQt_xufang", "0"))
    def show(self,Ui_PyQt_xufang):
        self.Displaytext.setPlainText("1")


